import Head from 'next/head';
import {BsFillMoonStarsFill} from 'react-icons/bs';
import {AiFillTwitterCircle, AiFillLinkedin, AiFillYoutube} from 'react-icons/ai';
import Image from "next/image";
import deved from "../public/dev-ed-wave.png";
import design from '../public/design.png';
import code from '../public/code.png';
import consulting from '../public/consulting.png';
import web1 from '../public/web1.png';
import web2 from '../public/web2.png';
import web3 from '../public/web3.png';
import web4 from '../public/web4.png';
import web5 from '../public/web5.png';
import web6 from '../public/web6.png';
import { useState } from 'react';

export default function Home() {
  const [darkMode, setDarkMode]= useState(false);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white px-10 md:px-20 lg:px-40 dark:bg-grey-900">
      <section className= "min-h-screen">
      <nav className='py-10 mb-12 flex justify-between'>
        <h1 className='text-xl font-burtons'>coaicac</h1>
        <ul className='flex items-center'>
          <li>
            <BsFillMoonStarsFill
             onClick={() => setDarkMode(!darkMode)}
             className='cursor-pointer text-2xl'/>
          </li>
          <li>
            <a className="bg-gradient-to-r from bg-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8">Resume</a></li>
        </ul>
      </nav>
      <div className='text-center p-10 '>
        <h2 className='text-5xl py-2 text-teal-600 font-medium md:text-6xl'>
          Rahat Nadeem
        </h2>
        <h3 className='text-2xl py-2 md:text-3xl'>
           Developer and Designer
           </h3>
        <p className='text-md py-5 leading-8 text-gray-800 md:text-xl max-w-l mx-auto' >
          A Computer Science Engineer Currently pursuing  B.E in Computer Science And Engineering at Loyola - ICAM College of Engineering and Technology.</p>
      </div>

      <div className='text-5xl flex justify-center gap-16 py-3 text-grey-600' >
        <AiFillTwitterCircle />
        <AiFillLinkedin />
        <AiFillYoutube />
      </div>
      <div className='relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 md:h-96 md:w-96 '>
        <Image src={deved} />
      </div>
      </section>
      
      <section>
        <div>
          <h3 className='text-3xl py-1'>About Me</h3>
          <p className='text-md py-2 leading-8 text-grey-80'> hicasic sa chsau  csgic  gsuc s gusc scius ciscz xl 
          schscks k
          csohcsc consulted for <span className='text-teal-500'>icasic sa chsau  csgic  gsuc s gusc scius ciscz xl 
          schs icasic sa chsau  csgic  gsuc s gusc scius ciscz xl 
          schscks k icasic sa chsau  csgic  gsuc s gusc scius ciscz xl 
          schscks kcks k</span>
          </p>
        </div>
        <div className='lg:flex gap-10'>
          <div className='text-center shadow-lg p-10 rounded-xl my-10'>
            <Image src={code} width={100} height={100} />
            <h3 className='text-lg font-medium pt-8 pb-2  text-teal-600'>Languages</h3>
            <p>
              Creating elegant design suited for you n design theory
            </p>
            <h4 className='py-4 text-teal-600'></h4>
            <p className='text-grey-800 py-1'>Python</p>
            <p className='text-grey-800 py-1'>Java</p>
            <p className='text-grey-800 py-1'>HTML</p>
            <p className='text-grey-800 py-1'>CSS</p>
            <p className='text-grey-800 py-1'>JavaScript</p>
            <p className='text-grey-800 py-1'>ReactJS</p>
            <p className='text-grey-800 py-1'>NextJS</p>
          </div>
          <div className='text-center shadow-lg p-10 rounded-xl my-10'>
            <Image src={consulting} width={100} height={100} />
            <h3 className='text-lg font-medium pt-8 pb-2  text-teal-600'>Databases</h3>
            <p>
            Creating elegant design suited for you n design theory
            </p>
            <h4 className='py-4 text-teal-600'>Databases I use</h4>
            <p className='text-grey-800 py-1'>MySQL</p>
            <p className='text-grey-800 py-1'>PostgreSQL</p>
            <p className='text-grey-800 py-1'></p>
            <p className='text-grey-800 py-1'></p>
          </div>
          <div className='text-center shadow-lg p-10 rounded-xl my-10'>
            <Image src={design} width={100} height={100} />
            <h3 className='text-lg font-medium pt-8 pb-2  text-teal-600 '>Designs</h3>
            <p>
              Creating elegant design suited for you !
            </p>
            <h4 className='py-4 text-teal-600'>Design tools I use</h4>
            <p className='text-grey-800 py-1'>Photoshop</p>
            <p className='text-grey-800 py-1'>Illustrator</p>
            <p className='text-grey-800 py-1'>FL Studio</p>
            <p className='text-grey-800 py-1'>Blender</p>
          </div>
        </div>
      </section>
      <section>
        <div>
          <h3 className='text-3xl py-1'>Projects & Works</h3>
          <p className='text-md py-2 leading-8 text-grey-80'> hicasic sa chsau  csgic  gsuc s gusc scius ciscz xl 
          schscks k
          csohcsc
          <span className='text-teal-500'> Agencies</span>
          consulted for <span className='text-teal-500'>icasic sa chsau  csgic  gsuc s gusc scius ciscz xl 
          schs icasic sa chsau  csgic  gsuc s gusc scius ciscz xl 
          schscks k icasic sa chsau  csgic  gsuc s gusc scius ciscz xl 
          schscks kcks k</span>
          </p>
          <p>I nask jnx san casbc sancjan scnaskx casbcsj scns  sacns saojc
          </p>
        </div>
        <div className='flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap'>
          <div className='basis-1/3 flex-1'>
            <Image 
            src={web3}
             className="rounded-lg object-cover"
             width={"100%"}
              height={'100%'}
              layout="responsive"/>
          </div>
          <div className='basis-1/3 flex-1'>
            <Image src={web5} 
            className="rounded-lg object-cover"
             width={'100%'}
              height={'100%'}
               layout="responsive"/>
          </div>
          <div className='basis-1/3 flex-1'>
            <Image src={web5}
             className="rounded-lg object-cover"
              width={'100%'}
               height={'100%'} 
               layout="responsive"/>
          </div>
          <div className='basis-1/3 flex-1'>
            <Image src={web3}
             className="rounded-lg object-cover" 
             width={'100%'} 
             height={'100%'}
            layout="responsive"/>
          </div>
          <div className='basis-1/3 flex-1'>
            <Image src={web3}
             className="rounded-lg object-cover"
              width={"100%"} 
              height={"100%"} 
              layout="responsive"/>
          </div>
          <div className='basis-1/3 flex-1'>
            <Image src={web2}
             className="rounded-lg object-cover"
              width={"100%"} 
              height={"100%"}
              layout="responsive"/>
          </div>
        </div>
      </section>
      </main>
    </div>
  );
}
